/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as ApiPublicVideoUrlRouteImport } from './routes/api/public/video-url'
import { Route as BatchesBatchIdIndexRouteImport } from './routes/batches.$batchId.index'
import { Route as ApiPublicPwSplatRouteImport } from './routes/api/public/pw.$'
import { Route as ApiPublicStreamSplatRouteImport } from './routes/api/public/stream.$'
import { Route as BatchesBatchIdSubjectSubjectIdIndexRouteImport } from './routes/batches.$batchId.subject.$subjectId.index'
import { Route as BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRouteImport } from './routes/batches.$batchId.subject.$subjectId.topic.$topicId.index'
import { Route as BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRouteImport } from './routes/batches.$batchId.subject.$subjectId.topic.$topicId.lecture.$lectureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideoUrlRoute = ApiPublicVideoUrlRouteImport.update({
  id: '/api/public/video-url',
  path: '/api/public/video-url',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdIndexRoute = BatchesBatchIdIndexRouteImport.update({
  id: '/batches/$batchId/',
  path: '/batches/$batchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPwSplatRoute = ApiPublicPwSplatRouteImport.update({
  id: '/api/public/pw/$',
  path: '/api/public/pw/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamSplatRoute = ApiPublicStreamSplatRouteImport.update({
  id: '/api/public/stream/$',
  path: '/api/public/stream/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdSubjectSubjectIdIndexRoute =
  BatchesBatchIdSubjectSubjectIdIndexRouteImport.update({
    id: '/batches/$batchId/subject/$subjectId/',
    path: '/batches/$batchId/subject/$subjectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRoute =
  BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRouteImport.update({
    id: '/batches/$batchId/subject/$subjectId/topic/$topicId/',
    path: '/batches/$batchId/subject/$subjectId/topic/$topicId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRoute =
  BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRouteImport.update({
    id: '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId',
    path: '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches/': typeof BatchesIndexRoute
  '/api/public/video-url': typeof ApiPublicVideoUrlRoute
  '/batches/$batchId/': typeof BatchesBatchIdIndexRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
  '/api/public/stream/$': typeof ApiPublicStreamSplatRoute
  '/batches/$batchId/subject/$subjectId/': typeof BatchesBatchIdSubjectSubjectIdIndexRoute
  '/batches/$batchId/subject/$subjectId/topic/$topicId/': typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRoute
  '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId': typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesIndexRoute
  '/api/public/video-url': typeof ApiPublicVideoUrlRoute
  '/batches/$batchId': typeof BatchesBatchIdIndexRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
  '/api/public/stream/$': typeof ApiPublicStreamSplatRoute
  '/batches/$batchId/subject/$subjectId': typeof BatchesBatchIdSubjectSubjectIdIndexRoute
  '/batches/$batchId/subject/$subjectId/topic/$topicId': typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRoute
  '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId': typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches/': typeof BatchesIndexRoute
  '/api/public/video-url': typeof ApiPublicVideoUrlRoute
  '/batches/$batchId/': typeof BatchesBatchIdIndexRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
  '/api/public/stream/$': typeof ApiPublicStreamSplatRoute
  '/batches/$batchId/subject/$subjectId/': typeof BatchesBatchIdSubjectSubjectIdIndexRoute
  '/batches/$batchId/subject/$subjectId/topic/$topicId/': typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRoute
  '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId': typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches/'
    | '/api/public/video-url'
    | '/batches/$batchId/'
    | '/api/public/pw/$'
    | '/api/public/stream/$'
    | '/batches/$batchId/subject/$subjectId/'
    | '/batches/$batchId/subject/$subjectId/topic/$topicId/'
    | '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/api/public/video-url'
    | '/batches/$batchId'
    | '/api/public/pw/$'
    | '/api/public/stream/$'
    | '/batches/$batchId/subject/$subjectId'
    | '/batches/$batchId/subject/$subjectId/topic/$topicId'
    | '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId'
  id:
    | '__root__'
    | '/'
    | '/batches/'
    | '/api/public/video-url'
    | '/batches/$batchId/'
    | '/api/public/pw/$'
    | '/api/public/stream/$'
    | '/batches/$batchId/subject/$subjectId/'
    | '/batches/$batchId/subject/$subjectId/topic/$topicId/'
    | '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  ApiPublicVideoUrlRoute: typeof ApiPublicVideoUrlRoute
  BatchesBatchIdIndexRoute: typeof BatchesBatchIdIndexRoute
  ApiPublicPwSplatRoute: typeof ApiPublicPwSplatRoute
  ApiPublicStreamSplatRoute: typeof ApiPublicStreamSplatRoute
  BatchesBatchIdSubjectSubjectIdIndexRoute: typeof BatchesBatchIdSubjectSubjectIdIndexRoute
  BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRoute: typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRoute
  BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRoute: typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video-url': {
      id: '/api/public/video-url'
      path: '/api/public/video-url'
      fullPath: '/api/public/video-url'
      preLoaderRoute: typeof ApiPublicVideoUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId/': {
      id: '/batches/$batchId/'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId/'
      preLoaderRoute: typeof BatchesBatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pw/$': {
      id: '/api/public/pw/$'
      path: '/api/public/pw/$'
      fullPath: '/api/public/pw/$'
      preLoaderRoute: typeof ApiPublicPwSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/$': {
      id: '/api/public/stream/$'
      path: '/api/public/stream/$'
      fullPath: '/api/public/stream/$'
      preLoaderRoute: typeof ApiPublicStreamSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId/subject/$subjectId/': {
      id: '/batches/$batchId/subject/$subjectId/'
      path: '/batches/$batchId/subject/$subjectId'
      fullPath: '/batches/$batchId/subject/$subjectId/'
      preLoaderRoute: typeof BatchesBatchIdSubjectSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId/subject/$subjectId/topic/$topicId/': {
      id: '/batches/$batchId/subject/$subjectId/topic/$topicId/'
      path: '/batches/$batchId/subject/$subjectId/topic/$topicId'
      fullPath: '/batches/$batchId/subject/$subjectId/topic/$topicId/'
      preLoaderRoute: typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId': {
      id: '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId'
      path: '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId'
      fullPath: '/batches/$batchId/subject/$subjectId/topic/$topicId/lecture/$lectureId'
      preLoaderRoute: typeof BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  ApiPublicVideoUrlRoute: ApiPublicVideoUrlRoute,
  BatchesBatchIdIndexRoute: BatchesBatchIdIndexRoute,
  ApiPublicPwSplatRoute: ApiPublicPwSplatRoute,
  ApiPublicStreamSplatRoute: ApiPublicStreamSplatRoute,
  BatchesBatchIdSubjectSubjectIdIndexRoute:
    BatchesBatchIdSubjectSubjectIdIndexRoute,
  BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRoute:
    BatchesBatchIdSubjectSubjectIdTopicTopicIdIndexRoute,
  BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRoute:
    BatchesBatchIdSubjectSubjectIdTopicTopicIdLectureLectureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
